services:
    postgres:
        build: ${image}
        container_name: ${container_name}
        environment:
            - POSTGRES_USERNAME=${user}
            - POSTGRES_PASSWORD=${password}
            - POSTGRES_DB=${database_name}
        ports:
            - ${host_port}:5432
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "psql -U ${user} -c 'SELECT 1' || exit 1"]
            interval: 5s
            retries: 5
            start_period: 10s
            timeout: 3s
    rules-generator:
        build: ${generate_rules_image}
        command: ["-f", "/app/coding_standard.yml", "-o", "/src/.sqlfluff"]
        volumes:
            - ./lint/coding_standard.yml:/app/coding_standard.yml
            - ./src:/src
    lint:
        build: ${sqlfluff_image}
        entrypoint: ["/bin/bash", "-c"]
        command: ["sqlfluff lint ${lint_verbosity} --write-output ${lint_output_path} /sql || true"]
        volumes:
            - ./src/:/sql
            - ./src/.sqlfluff:/sqlfluff/.sqlfluff
            - ./lint/:/lint/
        depends_on:
            rules-generator:
                condition: service_completed_successfully
    flyway:
        image: ${flyway_image}
        command: migrate
        environment:
            - FLYWAY_URL=jdbc:postgresql://${container_name}:${host_port}/${database_name}
            - FLYWAY_USER=${user}
            - FLYWAY_PASSWORD=${password}
            - FLYWAY_DEFAULT_SCHEMA=${default_schema}
            - FLYWAY_SQL_MIGRATION_PREFIX=${sql_migration_prefix}
            - FLYWAY_REPEATABLE_SQL_MIGRATION_PREFIX=${repeatable_sql_migration_prefix}
            - FLYWAY_MIXED=${mixed}
            - FLYWAY_PLACEHOLDERS_environment_name=${environment_name}
        volumes:
            - ./src/:/flyway/sql
        depends_on:
            lint:
                condition: service_completed_successfully
            postgres:
                condition: service_healthy
    cover_trace:
        build: ${coverage_image}
        command: ["trace", "-H", "${container_name}", "-p", "${host_port}", "-d", "${database_name}", "-U", "${user}", "-W", "${password}", "-c", "/coverage/cache"]
        volumes:
            - ./coverage/:/coverage/
        depends_on:
            flyway:
                condition: "service_completed_successfully"
    unit_test:
        build: ${image}
        environment:
            - PGPASSWORD=${password}
        volumes:
            - ./test/:/var/lib/postgresql/test_cases
            - ./coverage/:/var/lib/postgresql/coverage
        depends_on:
            cover_trace:
                condition: "service_completed_successfully"
        command: >
            bash -c "pg_prove --nocount --nocolor
            --host ${container_name} --username ${user} --port ${host_port}
            --dbname ${database_name} --ext .sql --recurse
            --failures /var/lib/postgresql/test_cases/
            2> /var/lib/postgresql/coverage/trace.txt"
    cover_report:
        build: ${coverage_image}
        command: ["report", "-H", "${container_name}", "-p", "${host_port}", "-d", "${database_name}", "-U", "${user}", "-W", "${password}", "-c", "/coverage/cache", "-f", "/coverage/trace.txt", "-o", "/coverage/opencover.xml"]
        volumes:
            - ./coverage/:/coverage/
        depends_on:
            unit_test:
                condition: "service_completed_successfully"
    cover_untrace:
        build: ${coverage_image}
        command: ["untrace", "-H", "${container_name}", "-p", "${host_port}", "-d", "${database_name}", "-U", "${user}", "-W", "${password}", "-c", "/coverage/cache"]
        volumes:
            - ./coverage/:/coverage/
        depends_on:
            cover_report:
                condition: "service_completed_successfully"


